### ISSUE TITLE
Failure at main()

### ISSUE THREAD

**Issue by charettepa** [LjMario007/Microsoft-Rewards-Bot#37]
started getting issues on April 1

completely wiped folder and started over again
cloned repo
reprocessed dependencies
getting bellow error everytime

:: ERROR :: root :: Failure at main()
Traceback (most recent call last):
  File "/rewards_bot/ms_rewards.py", line 900, in <module>
    browser = browser_setup(parser.headless_setting, MOBILE_USER_AGENT)
  File "/rewards_bot/ms_rewards.py", line 266, in browser_setup
    chrome_obj = webdriver.Chrome(path, options=options)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81
  (Driver info: chromedriver=81.0.4044.69 (6813546031a4bc83f717a2ef7cd4ac6ec1199132-refs/branch-heads/4044@{#776}),platform=Linux 4.4.59+ x86_64)

**Comment by LxanderUA** [comment]
Did you try to update Chrome Browser?

**Comment by charettepa** [comment]
This is strange
i had the same issue in my docker container and on my windows workstation
since updating chrome in windows it now works there again
however the docker container still fails with the same error
how do i fix the docker container?

**Comment by LxanderUA** [comment]
Building new container will be best solution, I think.

**Comment by charettepa** [comment]
I did that late last night
built my own
mukowman's has not been updated in 5 months
it seems that a new one will be needed every now and then once chrome gets too old

**Comment by LxanderUA** [comment]
just don't upgrade nor Chrome nor ChromeDriver

**Comment by koderian** [comment]
I am getting failure at main() too. The bot still works however there’s been a bunch of errors like this
