### ISSUE TITLE
Logs not displaying points - Unable to Locate Element

### ISSUE THREAD

**Issue by TK7K** [LjMario007/Microsoft-Rewards-Bot#40]
### Lately on most PC and Mobile searches I am getting an error like below. Sometimes it works, but most have errors. When I login in to that account, it appears to have completed the searches, but just does not display points in the logs correctly. Its good that points are gathered, but just harder to track when an account is ready to harvest. Anyone else having this issue or has resolved this on their end?

`2020-05-04 08:02:38,191 :: INFO :: root :: -------------------------MOBILE-------------------------
2020-05-04 08:02:40,549 :: INFO :: root :: Logging in XXXXX@XXX.com...
2020-05-04 08:03:26,660 :: INFO :: root :: Number of open offers: 6
2020-05-04 08:05:58,142 :: ERROR :: root :: Webdriver Error for send key by class to wk_button object
Traceback (most recent call last):
  File "ms_rewards.py", line 451, in click_by_class
    browser.find_element_by_class_name(selector).click()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"wk_button"}
  (Session info: headless chrome=81.0.4044.129)
  (Driver info: chromedriver=81.0.4044.129 (3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}),platform=Linux 5.4.0-1008-raspi aarch64)

**Comment by TK7K** [comment]
Disregard, It seems as though the issue worked it's self out. I am seeing clean logs now.
