### ISSUE TITLE
Webdriver Errors

### ISSUE THREAD

**Issue by jdhdur** [LjMario007/Microsoft-Rewards-Bot#49]
2020-07-07 10:26:47,864 :: ERROR :: root :: WebDriverException while executing pc portion
Traceback (most recent call last):
  File "ms_rewards.py", line 944, in <module>
    iter_dailies()
  File "ms_rewards.py", line 609, in iter_dailies
    offer.click()
  File "C:\Users\I\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\I\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\I\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\I\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=83.0.4103.116)
  (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Windows NT 10.0.19041 x86_64)

2020-07-08 10:20:56,035 :: ERROR :: root :: wk_button element Not clickable - Timeout Exception
2020-07-08 10:20:56,035 :: ERROR :: root :: wk_button cannot be located.
Traceback (most recent call last):
  File "ms_rewards.py", line 395, in wait_until_clickable
    WebDriverWait(browser, time_to_wait).until(ec.element_to_be_clickable((by_, selector)))
  File "C:\Users\I\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

![20200708%H2056_wk_button](https://user-images.githubusercontent.com/65252409/86939953-36212200-c110-11ea-8709-634d71047e06.png)

2020-07-08 10:20:56,358 :: ERROR :: root :: Webdriver Error for send key by class to wk_button object
Traceback (most recent call last):
  File "ms_rewards.py", line 455, in click_by_class
    browser.find_element_by_class_name(selector).click()
  File "C:\Users\I\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "C:\Users\I\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\I\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\I\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"wk_button"}
  (Session info: chrome=83.0.4103.116)
  (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Windows NT 10.0.19041 x86_64)

**Comment by velotoxicsounds** [comment]
Same:

2020-07-16 17:23:29,070 :: INFO :: root :: --------------------------------------------------
2020-07-16 17:23:29,071 :: INFO :: root :: -----------------------New------------------------
2020-07-16 17:23:29,071 :: INFO :: root :: --------------------------------------------------
2020-07-16 17:23:29,071 :: INFO :: root :: logins retrieved.
2020-07-16 17:23:44,937 :: INFO :: root :: # of search items: 142

2020-07-16 17:23:44,937 :: INFO :: root :: -------------------------MOBILE-------------------------
2020-07-16 17:23:49,136 :: ERROR :: root :: Failure at main()
Traceback (most recent call last):
  File "ms_rewards.py", line 905, in <module>
    browser = browser_setup(parser.headless_setting, MOBILE_USER_AGENT)
  File "ms_rewards.py", line 270, in browser_setup
    chrome_obj = webdriver.Chrome(path, options=options)
  File "C:\Users\velot\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Users\velot\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\velot\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\velot\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\velot\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 84
  (Driver info: chromedriver=84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310}),platform=Windows NT 10.0.20161 x86_64)
