### ISSUE TITLE
Stopped doing PC searches and middle daily-set

### ISSUE THREAD

**Issue by koderian** [LjMario007/Microsoft-Rewards-Bot#56]
![image](https://user-images.githubusercontent.com/44537031/93277940-f5bcd080-f75e-11ea-85ca-0a5b2edcc1cf.png)
 
![image](https://user-images.githubusercontent.com/44537031/93277958-053c1980-f75f-11ea-97db-8d1583e6acae.png)

**Comment by LxanderUA** [comment]
Try to set --log-level DEBUG
Check ./logs/ms_rewards.log

**Comment by LiaMaps** [comment]
Seems like it is an region or locale problem. For some reason it switches to other locale then en-US, so e.g. "Sign in" is not findeable. Sign in Prompt screenshot shows the login Button in locale language.

**Comment by LiaMaps** [comment]
This is the first error occoruing:
`2020-09-17 07:53:53,249 :: ERROR :: root :: //input[@type='submit'] element Not clickable - Timeout Exception
2020-09-17 07:53:53,249 :: ERROR :: root :: //input[@type='submit'] cannot be located.
Traceback (most recent call last):
  File "/home/poo/Microsoft-Rewards-Bot/ms_rewards.py", line 430, in wait_until_clickable
    ec.element_to_be_clickable((by_, selector)))
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: `

**Comment by martymcfly1955** [comment]
Not sure which branch you have, but mine includes the def below to make sure you're logged in before the search runs.  For a time, my pc search was doing the same thing as yours until I increased the time.sleep from .1 to 1.  It was basically trying to click that login link before it rendered.  


def ensure_pc_mode_logged_in():
    """
    Navigates to www.bing.com and clicks on ribbon to ensure logged in
    PC mode for some reason sometimes does not fully recognize that the user is logged in
    :return: None
    """
    browser.get(BING_SEARCH_URL)
    # time.sleep(0.1)
    time.sleep(1)
    # click on ribbon to ensure logged in
    wait_until_clickable(By.ID, 'id_l', 15)
    click_by_id('id_l')
    time.sleep(0.1)

**Comment by coollbv** [comment]
It just started happening to me. When I manually go to that middle quiz I get a log in page and every time I click on Sign In it gives me HTTP 400 Bad Request page. I wander if it's something on MS end.

**Comment by ZeroCool940711** [comment]
For me the bot stopped doing the daily set, never completes the last one, it's not doing the Mobile searches and Edge searches neither.
![image](https://user-images.githubusercontent.com/5977640/95515288-3a104a80-0972-11eb-9a78-3554d85af860.png)
![image](https://user-images.githubusercontent.com/5977640/95515313-41375880-0972-11eb-9149-ed0d70f63d3a.png)

**Comment by coollbv** [comment]
I updated my Chrome (I had 85 not 86) and using @velotoxicsounds branch and I am getting the same - the Sign In button actually logs in (it doesn't go to HTTP 400 Bad Request page) but that pesky Daily Poll won't complete...

**Comment by hidingfromu** [comment]
> I updated my Chrome (I had 85 not 86) and using @velotoxicsounds branch and I am getting the same - the Sign In button actually logs in (it doesn't go to HTTP 400 Bad Request page) but that pesky Daily Poll won't complete...

Hi,

I've tried using both versions, and I get the above errors, plus the bot won't detect the current points attained so does 150 searches for both PC and Mobile. 1 account takes 2 hours plus.

**Comment by velotoxicsounds** [comment]
you can use my fork. I missed an update to him today. The points are now read correctly. I have also fixed the problem that no points will be awarded.

Watch here
https://github.com/LjMario007/Microsoft-Rewards-Bot/pull/64

**Comment by keepthecyphe** [comment]
@velotoxicsounds's fork is also having issues with the daily poll. it's reading search points correctly if you follow my pull request and completing them fast. @kowshika-n's fork seems to complete the daily set just fine, but run-time is 2hours+ per account. if i have time i'll try to debug and merge the two into a working result

**Comment by velotoxicsounds** [comment]
@keepthecyphe

Do you use my current version? What error do you have in your log? For me, the dailys work again


MS-RewardBot:
Search Start

Stopped at search number 45

Number of open offers: 5

Number of incomplete offers remaining: 1

Total points = 2

PC points = 90/90

Edge points = 12/12

Mobile points = 60/60
